blank_issues_enabled: false
contact_links:

  - name: Get Help
    url: https://www.jetporch.com/community/discord-chat
    about: Discord Chat
  - name: Ask Questions
    url: https://www.jetporch.com/community/discord-chat
    about: Discord Chat
  - name: Make A Feature Request
    url: https://www.jetporch.com/community/discord-chat
    about: Discord Chat
  - name: Discuss Development or Feature Ideas
    url: https://www.jetporch.com/community/discord-chat
    about: Discord Chat
  - name: Contributor Guide
    url: https://www.jetporch.com/community/contributing
    about: Required reading


